version: 1.5.2
port: 7054
debug: false

tls:
  enabled: true
  certfile: ${TLS_CERT}
  keyfile: ${TLS_KEY}
  clientauth:
    type: RequireAndVerifyClientCert
    certfiles:
      -  ${CA_CERT}

ca:
  name: RootCA
  keyfile: ${CA_KEY}
  certfile: ${CA_KEY}
  chainfile: ${CA_CHAIN}

crl:
  expiry: 24h

registry:
  maxenrollments: -1
  identities:
    - name: admin
      pass: adminpw
      type: client
      affiliation: ""
      attrs:
        hf.Registrar.Roles: "*"
        hf.Registrar.DelegateRoles: "*"
        hf.Revoker: true
        hf.IntermediateCA: true
        hf.GenCRL: true
        hf.Registrar.Attributes: "*"
        hf.AffiliationMgr: true

signing:
  default:
    usage:
      - digital signature
    expiry: 8760h
  profiles:
    ca:
      usage:
        - cert sign
        - crl sign
      expiry: 87600h
      caconstraint:
        isca: true
        maxpathlen: 1

csr:
  cn: ca.pesachain.com
  keyrequest:
    algo: ecdsa
    size: 256
  names:
    - C: KE
      ST: Nairobi
      L: Nairobi
      O: Pesachain
      OU: Blockchain
  ca:
    expiry: 87600h
    pathlength: 1