# Development Stage
FROM node:18-alpine AS base

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# Use the base image for development
FROM base AS dev

EXPOSE 3000

RUN adduser -D appuser
USER appuser

CMD ["npm", "start"]
