# Production Stage
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY . .

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 3000

RUN adduser -D appuser
USER appuser

CMD ["npm", "start"]
