OrdererOrgs:
  - Name: OrdererOrg
    Domain: pesachain.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2

PeerOrgs:
  - Name: Pesachain
    Domain: pesachain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1