# License section (optional but recommended)
#########################################################################
#   Licensed under the Apache License, Version 2.0 (the "License");     #
#   you may not use this file except in compliance with the License.     #
#   You may obtain a copy of the License at                              #
#                                                                        #
#       http://www.apache.org/licenses/LICENSE-2.0                       #
#                                                                        #
#   Unless required by applicable law or agreed to in writing, software  #
#   distributed under the License is distributed on an "AS IS" BASIS,    #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or      #
#   implied. See the License for the specific language governing         #
#   permissions and limitations under the License.                       #
#########################################################################

version: 1.4.0

#############################################################################
# The root CA configuration section
#############################################################################
debug: false

# The listening address of the Fabric CA server
port: 7054

# Enables logging of client certificate information (CN, issuer CN, SANs) at the INFO level
clientauth:
  type: noclientcert

#############################################################################
# Server's Certificate and Key file paths (TLS configuration)
#############################################################################
tls:
  enabled: false

#############################################################################
# Configuration of the CA registry (database of identities)
#############################################################################
registry:
  maxenrollments: -1  # Unlimited enrollments
  identities:
    - name: admin
      pass: adminpw
      type: client
      affiliation: ""
      attrs:
        hf.Registrar.Roles: "client,peer,orderer,admin,user"
        hf.Registrar.DelegateRoles: "client,peer,orderer,admin,user"
        hf.Revoker: true
        hf.IntermediateCA: true
        hf.GenCRL: true
        hf.Registrar.Attributes: "*"
        hf.AffiliationMgr: true

#############################################################################
# Database configuration
#############################################################################
db:
  type: sqlite3
  datasource: fabric-ca-server.db
  tls:
    enabled: false

#############################################################################
# The CFG section is where customizations are specified
#############################################################################
cacount: 1  # Number of CAs to serve

#############################################################################
# CA configuration
#############################################################################
ca:
  # CA name
  name: ca.pesachain.com

  # Key file and certificate for the CA's signing key pair
  keyfile: ca-key.pem
  certfile: ca-cert.pem

  # CRL (Certificate Revocation List) configuration
  crl:
    expiry: 24h

#############################################################################
# Affiliation settings
#############################################################################
affiliations:
  pesachain:
    - department1
    - department2
  bank:
    - bankA
    - bankB
  paymentgateway:
    - gatewayA
    - gatewayB

#############################################################################
# Signing configuration
#############################################################################
signing:
  default:
    usage:
      - digital signature
      - key encipherment
      - key agreement
    expiry: 8760h  # 1 year
  profiles:
    tls:
      usage:
        - digital signature
        - key encipherment
      expiry: 8760h
    ca:
      usage:
        - cert sign
        - crl sign
      expiry: 43800h  # 5 years
      caconstraint:
        isca: true
        maxpathlen: 0

#############################################################################
# Certificate Signing Request (CSR) section
#############################################################################
csr:
  cn: ca.pesachain.com
  names:
    - C: US
      ST: California
      L: San Francisco
      O: Pesachain
      OU: Fabric
  hosts:
    - localhost
    - ca.pesachain.com
  ca:
    expiry: 131400h  # 15 years
    pathlen: 1

#############################################################################
# LDAP configuration (if integrating with LDAP)
#############################################################################
ldap:
  enabled: false
  url: ldap://<adminDN>:<adminPassword>@<host>:<port>/<base>
  attribute:
    names:
      - uid
      - memberOf

#############################################################################
# BCCSP (Blockchain Cryptographic Service Provider) settings
#############################################################################
bccsp:
  default: SW
  sw:
    Hash: SHA2
    Security: 256

#############################################################################
# Metrics configuration
#############################################################################
metrics:
  provider: prometheus
  prometheus:
    endpoint: 0.0.0.0:8888
    enabled: true

#############################################################################
# Operations service configuration
#############################################################################
operations:
  listenAddress: 127.0.0.1:9443
  tls:
    enabled: false
