apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-ca
  namespace: fabric-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-ca
  template:
    metadata:
      labels:
        app: fabric-ca
    spec:
      containers:
      - name: fabric-ca
        image: hyperledger/fabric-ca
        env:
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        ports:
        - containerPort: 7054
        volumeMounts:
        - name: fabric-ca
          mountPath: /etc/hyperledger/fabric-ca-server
      volumes:
      - name: fabric-ca
        persistentVolumeClaim:
          claimName: ca-pvc
