apiVersion: v1
kind: Service
metadata:
  name: fabric-ca-service
  namespace: fabric-ca
spec:
  selector:
    app: fabric-ca
  ports:
  - protocol: TCP
    port: 7054
    targetPort: 7054
  type: NodePort
