apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer0-pesachain
  namespace: pesachain
spec:
  serviceName: "peer0"
  replicas: 1
  selector:
    matchLabels:
      app: peer0
  template:
    metadata:
      labels:
        app: peer0
    spec:
      containers:
      - name: peer0
        image: hyperledger/fabric-peer
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: peerdata
          mountPath: /var/hyperledger/production
  volumeClaimTemplates:
  - metadata:
      name: peerdata
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
