version: 1.5.2
port: 7054
debug: false

tls:
  enabled: true
  certfile: ../../network/crypto-config/peerOrganizations/org.pesachain.com/tlsca/tlsca.org.pesachain.com-cert.pem
  keyfile: ../../network/crypto-config/peerOrganizations/org.pesachain.com/tlsca/priv_sk
  clientauth:
    type: RequireAndVerifyClientCert
    certfiles:
      -  ../../network/crypto-config/peerOrganizations/org.pesachain.com/ca/ca.org.pesachain.com-cert.pem

ca:
  name: RootCA
  keyfile: ca-key.pem
  certfile: ca-cert.pem
  chainfile: ca-chain.pem

crl:
  expiry: 24h

registry:
  maxenrollments: -1
  identities:
    - name: admin
      pass: adminpw
      type: client
      affiliation: ""
      attrs:
        hf.Registrar.Roles: "*"
        hf.Registrar.DelegateRoles: "*"
        hf.Revoker: true
        hf.IntermediateCA: true
        hf.GenCRL: true
        hf.Registrar.Attributes: "*"
        hf.AffiliationMgr: true

signing:
  default:
    usage:
      - digital signature
    expiry: 8760h
  profiles:
    ca:
      usage:
        - cert sign
        - crl sign
      expiry: 87600h
      caconstraint:
        isca: true
        maxpathlen: 1

csr:
  cn: ca.pesachain.com
  keyrequest:
    algo: ecdsa
    size: 256
  names:
    - C: US
      ST: California
      L: San Francisco
      O: Pesachain
      OU: Blockchain
  ca:
    expiry: 87600h
    pathlength: 1