apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-peer0-pesachain
  namespace: pesachain
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/peer0-pesachain"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-peer0-pesachain
  namespace: pesachain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
