name: CD Pipeline for Pesa-chain

on:
  push:
    branches:
      - master
      - develop
      - maintenance
      - release/*
      - hotfix/*

jobs:
  # Development Deployment
  deploy-to-development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Select Tagging Scheme
        id: get_tag
        run: |
          TAG=$(git tag --points-at HEAD)
          if [ -z "$TAG" ]; then
            echo "No tags found in the latest commit. Using commit hash."
            echo "git_tag=${GITHUB_SHA}" >> $GITHUB_ENV
          else
            echo "Using tag from the latest commit: $TAG"
            echo "git_tag=$TAG" >> $GITHUB_ENV
          fi

      - name: Set IMAGE_TAG for Development
        run: |
          echo "IMAGE_TAG=$IMAGE_TAG"
          echo "IMAGE_TAG=dev-${{ env.git_tag }}" >> $GITHUB_ENV

      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1

      # Parallel deployment of Docker images for development
      - name: Deploy Pesachain (Dev)
        run: |
          docker compose -f docker-compose.yml pull
          docker compose -f docker-compose.yml up -d

      # Wait for services to start
      - name: Wait for Services to Start
        run: sleep 60

      # Health Checks
      - name: Health Check for Blockchain Service
        run: |
          if ! curl --fail http://localhost:4000/health; then
            echo "Blockchain service health check failed. Investigate the issue."
            exit 1
          fi

      - name: Health Check for Backend Service
        run: |
          if ! curl --fail http://localhost:3000/health; then
            echo "Backend service health check failed. Investigate the issue."
            exit 1
          fi

      - name: Health Check for Web Service
        run: |
          if ! curl --fail http://localhost:8080; then
            echo "Web service health check failed. Investigate the issue."
            exit 1
          fi

      - name: Health Check for Mobile Service
        run: |
          if ! curl --fail http://localhost:8081; then
            echo "Mobile service health check failed. Investigate the issue."
            exit 1
          fi

  # Staging Deployment
  deploy-to-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release/*'
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Select Tagging Scheme
        id: get_tag
        run: |
          TAG=$(git tag --points-at HEAD)
          if [ -z "$TAG" ]; then
            echo "No tags found in the latest commit. Using commit hash."
            echo "git_tag=${GITHUB_SHA}" >> $GITHUB_ENV
          else
            echo "Using tag from the latest commit: $TAG"
            echo "git_tag=$TAG" >> $GITHUB_ENV
          fi

      - name: Set IMAGE_TAG for Staging
        run: |
            echo "IMAGE_TAG=$IMAGE_TAG"
            echo "IMAGE_TAG=stag-${{ env.git_tag }}" >> $GITHUB_ENV

      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1

      # Parallel deployment of Docker images for development
      - name: Deploy Pesachain (Stag)
        run: |
          docker compose -f docker-compose.yml pull
          docker compose -f docker-compose.yml up -d

      # Wait for services to start
      - name: Wait for Services to Start
        run: sleep 60

      # Health Checks
      - name: Health Check for Backend Service
        run: |
          if ! curl --fail http://localhost:3000/health; then
            echo "Backend service health check failed. Investigate the issue."
            exit 1
          fi

      - name: Health Check for Blockchain Service
        run: |
          if ! curl --fail http://localhost:4000/health; then
            echo "Blockchain service health check failed. Investigate the issue."
            exit 1
          fi

      - name: Health Check for Web Service
        run: |
          if ! curl --fail http://localhost:8080; then
            echo "Web service health check failed. Investigate the issue."
            exit 1
          fi

      - name: Health Check for Mobile Service
        run: |
          if ! curl --fail http://localhost:8081; then
            echo "Mobile service health check failed. Investigate the issue."
            exit 1
          fi

  # Production Deployment
  deploy-to-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Select Tagging Scheme
        id: get_tag
        run: |
          TAG=$(git tag --points-at HEAD)
          if [ -z "$TAG" ]; then
            echo "No tags found in the latest commit. Using commit hash."
            echo "git_tag=${GITHUB_SHA}" >> $GITHUB_ENV
          else
            echo "Using tag from the latest commit: $TAG"
            echo "git_tag=$TAG" >> $GITHUB_ENV
          fi

      - name: Set IMAGE_TAG for Production
        run: |
            echo "IMAGE_TAG=$IMAGE_TAG"
            echo "IMAGE_TAG=dev-${{ env.git_tag }}" >> $GITHUB_ENV

      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1

      # Parallel deployment of Docker images for development
      - name: Deploy Pesachain (Prod)
        run: |
          docker compose -f docker-compose.yml pull
          docker compose -f docker-compose.yml up -d

      # Wait for services to start
      - name: Wait for Services to Start
        run: sleep 60

      # Health checks
      - name: Health Check for Backend Service
        run: |
          if ! curl --fail http://localhost:3000/health; then
            echo "Backend service health check failed. Investigate the issue."
            exit 1
          fi

      - name: Health Check for Blockchain Service
        run: |
          if ! curl --fail http://localhost:4000/health; then
            echo "Blockchain service health check failed. Investigate the issue."
            exit 1
          fi

      - name: Health Check for Web Service
        run: |
          if ! curl --fail http://localhost:8080; then
            echo "Web service health check failed. Investigate the issue."
            exit 1
          fi

      - name: Health Check for Mobile Service
        run: |
          if ! curl --fail http://localhost:8081; then
            echo "Mobile service health check failed. Investigate the issue."
            exit 1
          fi
