name: CD Pipeline for Pesa-chain

on:
  push:
    branches:
      - master
      - develop
      - release/*
      - hotfix/*

jobs:
  deploy-to-development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment:
      name: development
      url: https://dev.moneyremittance.example.com
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Deploy to Development
      run: |
        echo "Deploying to development..."
        # Add deployment script here

  deploy-to-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release/*'
    environment:
      name: staging
      url: https://staging.moneyremittance.example.com
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Deploy to Staging
      run: |
        echo "Deploying to staging..."
        # Add deployment script here

  deploy-to-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment:
      name: production
      url: https://www.moneyremittance.example.com
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        # Add deployment script here

  deploy-to-hotfix:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/hotfix/*'
    environment:
      name: production
      url: https://www.moneyremittance.example.com
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Deploy Hotfix to Production
      run: |
        echo "Deploying hotfix to production..."
        # Add deployment script here