name: CD Pipeline for Pesa-chain

on:
  push:
    branches:
      - master
      - develop
      - maintenance
      - release/*
      - hotfix/*

jobs:
  deploy-to-development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Development Docker Image
        run: docker pull myapp-dev:${{ github.sha }}

      - name: Run Development Docker Container
        run: |
          docker run -d --name myapp-dev -p 3000:3000 myapp-dev:${{ github.sha }}

  deploy-to-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release/*'
    environment:
      name: staging
      url: https://staging.moneyremittance.example.com
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Deploy to Staging
      run: |
        echo "Deploying to staging..."
        # Add deployment script here

  deploy-to-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Production Docker Image
        run: docker pull myapp-prod:${{ github.sha }}

      - name: Run Production Docker Container
        run: |
          docker run -d --name myapp-prod -p 80:3000 myapp-prod:${{ github.sha }}


  deploy-to-hotfix:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/hotfix/*'
    environment:
      name: production
      url: https://www.moneyremittance.example.com
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Deploy Hotfix to Production
      run: |
        echo "Deploying hotfix to production..."
        # Add deployment script here