name: CI Pipeline for Pesa-chain

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - release/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - release/*
      - hotfix/*
  schedule:
    - cron: '35 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  semgrep:
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Semgrep Scan
        run: semgrep ci
